spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.47.135:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  config:
    import:
      - nacos:default.properties?refresh=true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: 1
      logic-not-delete-value: 0

server:
  port: 11000