spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: 8b43fdd6-ad39-4a2e-99ca-d080ddf2408f
  application:
    name: gulimall-gateway
  config:
    import:
      - nacos:gulimall-gateway.yml?refresh=true

server:
  port: 88
